# Generated by Django 3.2.20 on 2023-12-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0002_auto_20231216_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('province', models.CharField(max_length=255)),
            ],
        ),
    ]
