# Generated by Django 3.2.20 on 2023-12-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_store_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('achieved', models.CharField(max_length=255)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_map')),
            ],
        ),
    ]
