# Generated by Django 3.2.20 on 2023-12-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0004_storeperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('branding_condition', models.CharField(blank=True, max_length=3)),
                ('disclaimer_signage_condition', models.CharField(blank=True, max_length=3)),
                ('noticed_campaigns', models.CharField(blank=True, max_length=3)),
                ('campaign_details', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
