# Generated by Django 3.2.20 on 2023-12-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0005_entranceevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceevaluation',
            name='store',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='entrance_evaluation', to='app_management.store'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='app_management.province'),
        ),
    ]
