# Generated by Django 3.2.20 on 2023-12-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0006_auto_20231217_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entranceevaluation',
            name='store',
        ),
        migrations.AlterField(
            model_name='entranceevaluation',
            name='branding_condition',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='entranceevaluation',
            name='disclaimer_signage_condition',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='entranceevaluation',
            name='noticed_campaigns',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.province'),
        ),
    ]
