# Generated by Django 3.2.20 on 2023-12-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0007_auto_20231217_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entranceevaluation',
            old_name='description',
            new_name='province',
        ),
        migrations.AddField(
            model_name='entranceevaluation',
            name='store',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entranceevaluation',
            name='branding_condition',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='entranceevaluation',
            name='disclaimer_signage_condition',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='entranceevaluation',
            name='noticed_campaigns',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
