# Generated by Django 3.2.20 on 2023-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0008_auto_20231217_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeperformance',
            name='achieved',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storeperformance',
            name='target',
            field=models.IntegerField(),
        ),
    ]
