# Generated by Django 3.2.20 on 2023-12-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0010_auto_20231223_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('achieved', models.IntegerField()),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_map')),
            ],
        ),
    ]
