# Generated by Django 3.2.20 on 2023-12-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0011_performance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
