# Generated by Django 3.2.20 on 2023-12-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0012_delete_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeperformance',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_map'),
        ),
    ]
