# Generated by Django 3.2.20 on 2023-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0015_storeperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_level',
            name='mc_dim_no',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
