# Generated by Django 3.2.20 on 2023-12-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0016_alter_store_level_mc_dim_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_level'),
        ),
        migrations.AlterField(
            model_name='drivethru',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_level'),
        ),
        migrations.AlterField(
            model_name='inside',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_level'),
        ),
        migrations.AlterField(
            model_name='mccafe',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_level'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_level'),
        ),
        migrations.AlterField(
            model_name='outside',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.store_level'),
        ),
    ]
