# Generated by Django 3.2.20 on 2023-12-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0017_auto_20231226_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inside',
            name='pop_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inside',
            name='promotion_image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
