# Generated by Django 3.2.20 on 2023-12-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0018_auto_20231226_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='outside',
            name='external_disclaimer_signage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
