# Generated by Django 3.2.20 on 2023-12-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0019_outside_external_disclaimer_signage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outside',
            name='external_disclaimer_signage',
            field=models.BooleanField(),
        ),
    ]
