# Generated by Django 3.2.20 on 2023-12-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0020_alter_outside_external_disclaimer_signage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outside',
            old_name='external_disclaimer_signage',
            new_name='branding_condition',
        ),
    ]
