# Generated by Django 3.2.20 on 2023-12-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0021_rename_external_disclaimer_signage_outside_branding_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outside',
            name='campaign',
            field=models.BooleanField(),
        ),
    ]
