# Generated by Django 3.2.20 on 2023-12-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0022_alter_outside_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_level',
            name='tel_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
