# Generated by Django 3.2.20 on 2023-12-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0023_alter_store_level_tel_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outside',
            name='mc_dim_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
