# Generated by Django 3.2.20 on 2023-12-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0024_alter_outside_mc_dim_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outside',
            name='outside_trans_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=255),
        ),
    ]
