# Generated by Django 3.2.20 on 2023-12-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0026_auto_20231228_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='mc_dim_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
