# Generated by Django 3.2.20 on 2023-12-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0027_alter_menu_mc_dim_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mccafe',
            name='mc_dim_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
