# Generated by Django 3.2.20 on 2023-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0028_alter_mccafe_mc_dim_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='mc_dim_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='drivethru',
            name='mc_dim_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
